#!/bin/bash

MF_MOD_NAME="mf"
MF_DEV_NAME="/dev/mf_dev0"

LS_MOD=$(lsmod | grep ${MF_MOD_NAME})
if [ -n "${LS_MOD}" ]
then
	rmmod ${MF_MOD_NAME}
fi


LS_DEV=$(ls /dev | grep mf_dev0)
if [ -n "${LS_DEV}" ]
then
	rm ${MF_DEV_NAME}
fi
